version: "3"

services:
  maxhealth-db:
    build:
      context: ../backend/sql
    restart: "always"
    ports:
      - "8081:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

  maxhealth-be:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      maxhealth-db:
        condition: service_healthy
    platform: linux/amd64

  maxhealth-fe:
    build:
      context: ../frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - maxhealth-be
    platform: linux/amd64
